backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Home Image", name: "homeImage", widget: "image"}
    - label: "Image"
      name: "image"
      file: "content/image.md"
      fields:
        - { 
            label: "Image Post", 
            name: "imagePost", 
            widget: "list",
            fields:
              [
                { label: "Image", name: "image", widget: "image"},
                { label: "Title", name: "title", widget: "text"},
                {label: "Fullscreen?", name: "fullscreen", widget: "boolean", required: false}
              ],
          }
    - label: "Video"
      name: "video"
      file: "content/video.md"
      fields:
        - { 
            label: "Video Post", 
            name: "videoPost", 
            widget: "list",
            fields:
              [
                { label: "Video Code e.g. ZgdrcoPbpSs", name: "url", widget: "string"},
                { label: "Title", name: "title", widget: "string"},
              ],
          }
    - label: "Ode"
      name: "ode"
      file: "content/ode.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
          

