backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home Page"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Home Image", name: "HomeImage", widget: "image"}
    - label: "Image"
      name: "image"
      file: "content/image.md"
      fields:
        - { label: "Image Post", name: "ImagePost", widget: "string"}